---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: ansible.platform
    version: 2.6.20251106
  - name: ansible.hub
    version: 1.0.4
  - name: ansible.controller
    version: 4.7.8
  - name: ansible.eda
    version: 2.11.0
  - name: infra.aap_configuration
    version: 4.2.0
