---
authors:
  - Eric Ames (ericcames)
dependencies:
  "ansible.posix": ">=2.1.0"
  "ansible.utils": ">=6.0.0"
  "ansible.platform": ">=2.6.20250924"
  "ansible.hub": ">=1.0.2"
  "ansible.controller": ">=4.7.1"
  "ansible.eda": ">=2.10.0"
  "infra.aap_configuration": ">=3.8.0"
license_file: LICENSE
name: aap_as_code
description: A showcase to Configuration as Code. This repo is designed to have a repeatable build process for Ansible Automation Platform sales demos. We are leveraging the work that the Red Hat Product Demos team is doing.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/aap.as.code
issues: https://github.com/ericcames/aap.as.code/issues
tags:
  - lab
  - cloud
  - amazon
  - aws
  - windows
  - dailydemo
  - ansible
  - automation
  - sales
  - panos
  - palo_alto
version: 1.0.0