---
eda_credentials:
  - name: Controller Credential
    description: AAP credentials
    credential_type: 'Red Hat Ansible Automation Platform'
    organization: "{{ my_organization }}"
    inputs:
      host: "{{ my_aap_url }}/api/controller/"
      password: "{{ my_ctrl_admin_password }}"
      username: "admin"
      verify_ssl: true

  - name: ServiceNow Event Stream
    description: ServiceNow event stream Credential
    credential_type: 'ServiceNow Event Stream'
    organization: "{{ my_organization }}"
